/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 11, 22 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 0.505368614465052, 0.6418140069723383, 0.4467306110933956 };
const float ei_classifier_anom_mean[3] = { 0.36569402392674516, 0.4238627455313902, 0.3148163451684206 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { -0.6793245673179626, -0.6421325206756592, -0.6606392860412598 }, 0.2846967753359825 },
	{ ( float[3] ) { -0.4301011860370636, -0.5205810070037842, -0.47115060687065125 }, 0.6434054576571749 },
	{ ( float[3] ) { 1.5818936824798584, 3.077038049697876, 1.092049479484558 }, 2.0938257746182356 },
	{ ( float[3] ) { 0.7680978178977966, 4.5439558029174805, 2.61286997795105 }, 2.344259919780165 },
	{ ( float[3] ) { -0.08570992201566696, 0.4621122181415558, -0.025536105036735535 }, 0.7709068310083882 },
	{ ( float[3] ) { 0.5124676823616028, 0.09439574927091599, 1.5237241983413696 }, 1.224453721598998 },
	{ ( float[3] ) { 5.163509368896484, 1.177135944366455, 1.374224305152893 }, 2.2303810287759456 },
	{ ( float[3] ) { 0.33536088466644287, -0.21368388831615448, -0.17760494351387024 }, 0.700893699726223 },
	{ ( float[3] ) { 2.634596824645996, 1.2173837423324585, 1.3482112884521484 }, 1.8051088960183497 },
	{ ( float[3] ) { 0.6322060823440552, 0.02861964888870716, 0.554533839225769 }, 0.8136395016898907 },
	{ ( float[3] ) { 0.03832004591822624, 1.3712010383605957, 0.10959713906049728 }, 1.1475243421896575 },
	{ ( float[3] ) { -0.08916132152080536, -0.21175284683704376, 0.5741279125213623 }, 0.9367032016195688 },
	{ ( float[3] ) { -0.266628235578537, -0.26182565093040466, -0.07129623740911484 }, 0.7162445973869774 },
	{ ( float[3] ) { 1.235422134399414, 1.4289933443069458, 0.6858556866645813 }, 1.4288181613349134 },
	{ ( float[3] ) { 1.4600838422775269, 2.059398889541626, 2.2060093879699707 }, 2.1796162922360987 },
	{ ( float[3] ) { 0.764875054359436, 0.6123577356338501, 0.03350788354873657 }, 1.0934090981291644 },
	{ ( float[3] ) { 1.7740546464920044, 0.22886455059051514, 0.947022020816803 }, 1.9378959301238434 },
	{ ( float[3] ) { 0.4334618151187897, 1.36323881149292, 1.3961611986160278 }, 1.1948949196483758 },
	{ ( float[3] ) { 1.2756587266921997, -0.12176526337862015, 0.007887682877480984 }, 2.0037952523980853 },
	{ ( float[3] ) { 0.3079279661178589, 2.78657865524292, 1.7247105836868286 }, 1.3194354870271816 },
	{ ( float[3] ) { 0.13308927416801453, 0.6280947327613831, 0.8373447060585022 }, 0.8669041802693346 },
	{ ( float[3] ) { 3.145695209503174, 1.6713241338729858, 4.389852046966553 }, 2.3465620048884204 },
	{ ( float[3] ) { 9.3717679977417, 2.5620248317718506, 8.57716178894043 }, 3.658065494881046 },
	{ ( float[3] ) { 4.303703308105469, 5.033770561218262, 1.372864842414856 }, 3.6534679971424904 },
	{ ( float[3] ) { 0.6131570935249329, 2.6270816326141357, 0.41184693574905396 }, 1.4456226865429613 },
	{ ( float[3] ) { 2.5798392295837402, 1.672040581703186, 10.014698028564453 }, 3.60008034527423 },
	{ ( float[3] ) { 0.5187937021255493, 0.4092814326286316, 3.368500232696533 }, 1.9118892886023058 },
	{ ( float[3] ) { 0.7175604104995728, 1.4881908893585205, 5.539040565490723 }, 1.75570882918689 },
	{ ( float[3] ) { 10.48579216003418, 1.0548166036605835, 2.3189640045166016 }, 2.933423337239226 },
	{ ( float[3] ) { 6.972959518432617, 2.5761866569519043, 5.204788684844971 }, 3.723327239097408 },
	{ ( float[3] ) { 2.940866470336914, 3.297189474105835, 6.4795427322387695 }, 2.4737090780816837 },
	{ ( float[3] ) { 4.110621452331543, 7.2524871826171875, 9.142709732055664 }, 3.8397357629201334 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
